### ISSUE TITLE
Importer does not support relaxed .json format VS uses sometimes.

### ISSUE THREAD

**Issue by Novocain1** [phonon/blender-vintagestory-json#1]
If a shape file has objects in the relaxed json format ie, `key: "value"`, the importer will crash.

**Comment by phonon** [comment]
Post which file is causing issues

**Comment by Novocain1** [comment]
> Post which file is causing issues
block/basic/cube-nozfight.json
added to zip since commenting does not support the upload of .json files.
[cube-nozfight.zip](https://github.com/phonon/blender-vintagestory-json/files/6565481/cube-nozfight.zip)

**Comment by phonon** [comment]
Added solution for now to try using simple regex substitution on parse fail to add quotes around unquoted keys, these are detected by just a colon so this solution will fail if any strings contain a colon.
